stream.recorder.format=flv
stream.recorder.video.codec=27
stream.recorder.audio.codec=86018
stream.recorder.pixel-format=0
stream.recorder.frame-rate=30
stream.recorder.video.bitrate=3000000
stream.recorder.audio.bitrate=160000
stream.recorder.gop-size=2
stream.recorder.option.preset=present
stream.recorder.option.preset.value=veryfast
stream.recorder.option.tune=tune
stream.recorder.option.tune.value=zerolatency